blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/aZKuas4
    about: For assistance with minor concerns, smaller questions or security concerns, feel free to join our Discord server and contact @Redstonecrafter0. If this is about a security issue, please do so according to our security policy.
