name: Documentation
description: An issue regarding documentation
title: '[Documentation] '
labels:
  - documentation
  - needs addressing
body:
  - type: textarea
    id: description
    attributes:
      label: Is your issue related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I don't know why [...] behaves like [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a suggestion
      options:
        - label: |
            This wasn't already suggested.
            (I have searched for it on GitHub)
          required: true
