on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  staging:
    uses: ./.github/workflows/build.yml
    with:
      build-command: publishMavenJavaPublicationToLocalRepository
      environment: 'development'
    permissions:
      packages: write
      contents: write
