on:
  push:
    branches:
      - master
jobs:
  native:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Install prerequisites
        run: |
          choco install ninja
      - name: Build native library
        shell: cmake -P {0}
        run: |
          set(ENV{CC} cl)
          set(ENV{CXX} cl)
          
          execute_process(
            COMMAND "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat" && set
            OUTPUT_FILE environment_script_output.txt
          )
          file(STRINGS environment_script_output.txt output_lines)
          foreach(line IN LISTS output_lines)
            if (line MATCHES "^([a-zA-Z0-9_-]+)=(.*)$")
              set(ENV{${CMAKE_MATCH_1}} "${CMAKE_MATCH_2}")
            endif()
          endforeach()
          
          execute_process(
            COMMAND cmake
              -S .
              -B build-win
              -D CMAKE_BUILD_TYPE=Release
              -D "CMAKE_SYSTEM_VERSION=10.0.19041.0"
              -G Ninja
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status")
          endif()
          
          execute_process(
            COMMAND cmake
              --build build-win
              --target MediaPlayerInfo
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status")
          endif()
      - name: Save native library to cache
        uses: actions/cache/save@v4
        id: cache
        with:
          path: build-win/MediaPlayerInfo.dll
          key: "native-win-${{ github.sha }}"
          enableCrossOsArchive: true
  build:
    runs-on: ubuntu-latest
    needs:
      - native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "NIGHTLY_COMMIT=$calculatedSha" >> $GITHUB_ENV
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Restore native Windows library from cache
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: build-win/MediaPlayerInfo.dll
          key: "native-win-${{ github.sha }}"
          enableCrossOsArchive: true
      - name: Copy dll to resources
        run: cp build-win/MediaPlayerInfo.dll src/main/resources/mediaplayerinfo/natives/win/
      - name: Build with Gradle
        run: ./gradlew clean build dokkaJavaDocJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*
