on:
  workflow_dispatch:
jobs:
  staging:
    uses: ./.github/workflows/build.yml
    with:
      build-command: publishMavenJavaPublicationToLocalRepository
      environment: 'production'
    permissions:
      packages: write
      contents: write
    secrets:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      MAVEN_AUTH: ${{ secrets.MAVEN_AUTH }}
